version: '3'

services:

  drone-server:
    container_name: drone-server
    image: 192.168.3.200:80/library/drone/drone:2.9.1
    ports:
      - 8081:80
    volumes:
      - /docker/drone-server/data:/data
    restart: always
    environment:
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}

      - DRONE_GITHUB_SERVER=${DRONE_GITHUB_SERVER}
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}

      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true

    extra_hosts:
      - cicd.internal.gen10.mly0110.org.cn:192.168.3.215

  drone-agent:
    container_name: drone-agent
    image: 192.168.3.200:80/library/drone/drone-runner-docker:1
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DRONE_RPC_HOST=${DRONE_RPC_HOST}
      - DRONE_RPC_PROTO=${DRONE_RPC_PROTO}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}

      - DRONE_RUNNER_CAPACITY=${DRONE_RUNNER_CAPACITY}
      - DRONE_RUNNER_NAME=${DRONE_RUNNER_NAME}

      - DRONE_USER_CREATE=${DRONE_USER_CREATE}

    extra_hosts:
      - cicd.internal.gen10.mly0110.org.cn:192.168.3.215